# -*- coding: utf-8 -*-
"""Traduções EN/ES dos Termos de Uso (cortesia; PT é a oficial)."""
from blocks import h2, p, ul, contact

def build_en():
    S="Section"; b=""
    b+=p("These Terms and Conditions apply to the MyDose app and the MyDose web platform, a solution offered by My Dose LLC, a company incorporated in Delaware — United States. By using the platform, you tacitly and fully agree to the provisions contained herein. If you are not comfortable accepting these T&C, you may not use the MyDose platform and services.", lead=True)
    b+=h2("Acceptance of Terms and Conditions","s1",cap=S+" 1")
    b+=p("1.1. These T&C contain important information and the user must read them before requesting activation of their membership to the app.")
    b+=p('1.2. The updated version is available on our portals or via e-mail at <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("1.3. When you check 'I have read and agree', you are stating that you have read, understood and agree to follow the rules.")
    b+=p("1.4. MyDose may modify these T&C at any time. Whenever there is a significant update, we will inform you via e-mail or notifications on the platform.")
    b+=p("1.5. Requirements for registration: provide a valid e-mail, an identification number, and declare that you are in physical and mental condition to participate in the Communities.")
    b+=p("1.6. Minors under 18 ('Minor Users') require the express consent of their legal guardian through a 'Linked Account'.")
    b+=h2("Definitions","s2",cap=S+" 2")
    b+=ul(["<strong>Content:</strong> everything users share (texts, photos, videos, audios, e-books)","<strong>Community:</strong> virtual space to share healthy habits","<strong>Private Community:</strong> created by Leaders to grow their business","<strong>Public Community:</strong> open to the public","<strong>MyDose Platform:</strong> applications for physical, nutritional and mental wellbeing journeys","<strong>User:</strong> individual with a profile on the platform","<strong>Leader User:</strong> person who subscribes to a plan to create Communities","<strong>Manager User:</strong> person who assists the Leader in managing the Community"])
    b+=h2("What MyDose Is","s3",cap=S+" 3")
    b+=p("3.1. The MyDose Platform offers physical, nutritional and mental wellbeing journeys, as well as health guidance.")
    b+=p("3.2. The user may share their journey and progress with other users, generating engagement and enhancing healthy practices.")
    b+=p("3.3. MyDose believes in the power of Community and collaboration to create and maintain healthy habits.")
    b+=p("3.4. MyDose is a digital platform focused on the efficient management of online Communities, providing tools for creation, customization and administration.")
    b+=h2("Membership Code","s4",cap=S+" 4")
    b+=p("4.1. The membership code is the User's e-mail.")
    b+=p("4.2. Membership is personal and non-transferable. The User is responsible for safeguarding the code, and disclosure to third parties is prohibited.")
    b+=p("4.3. The User must immediately notify MyDose of any unauthorized use.")
    b+=p("4.4. The User agrees to:")
    b+=ul(["Not use the platform for fraudulent or illegal purposes","Notify of any unauthorized use","Request a new password if compromise is suspected","Use the platform in good faith"])
    b+=h2("Services Provided","s5",cap=S+" 5")
    b+=p("5.1. MyDose grants a personal, non-exclusive and non-transferable license to use the Services.")
    b+=p("5.2. The platform allows:")
    b+=ul(["Creation and management of gamified Communities","Tools for behavioral change","Rewards and recognition system","Analytics and progress reports","Integration with third-party tools","Interactions with artificial intelligence","Communication and engagement features"])
    b+=p("5.3. New features may be added and existing ones modified at any time.")
    b+=h2("Plans and Cancellation","s6",cap=S+" 6")
    b+=p("6.1. Users may participate free of charge in Public and Private Communities.")
    b+=p("6.2. Leader Users subscribe to plans (monthly, quarterly, semi-annual or annual).")
    b+=p("6.3. All plans RENEW AUTOMATICALLY until a cancellation request is made.")
    b+=p("7.1. Leader Users may cancel at any time, with effect until the next renewal.")
    b+=p("7.2. Refund available within 7 days of payment. After this period, no refund is available.")
    b+=p('7.5. CANCELLATION REQUESTS must be sent by e-mail to <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a> at least 20 days before renewal.')
    b+=h2("Obligations and Responsibilities","s7",cap=S+" 7")
    b+=p("8.1. The user is responsible for all statements, content entered and interactions carried out.")
    b+=p("8.2. Prohibited conduct includes:")
    b+=ul(["Publishing incorrect information or creating a false identity","Using another person's account","Reverse-engineering the app","Interfering with the operation or security","Accessing unauthorized areas","Using bots, scripts or data scraping","Harassing or harming other users","Violating intellectual property rights"])
    b+=p("8.3. Prohibited content: third-party data without authorization, illegal or discriminatory content, viruses or malware.")
    b+=h2("Limitation of Liability","s8",cap=S+" 8")
    b+=p("9.1. MyDose is not responsible for incorrect or incomplete data provided.")
    b+=p("9.2. The app does NOT replace medical, nutritional or health professional care. The User is responsible for their own health.")
    b+=p("9.3. MyDose disclaims liability for acts of Leader Users and Users that cause harm.")
    b+=p("9.4. MyDose is not responsible for content posted in the Communities.")
    b+=p("9.5. Contracts between Leader Users and Users do not bind MyDose.")
    b+=p("9.10. Leader Users are responsible for administering their communities ethically and for the entire relationship with their Users.")
    b+=h2("MyDose Artificial Intelligence","s9",cap=S+" 9")
    b+=p("10.1. Parts of the services may include artificial intelligence or machine learning technologies.")
    b+=p("10.2. MyDose works to make the services more accurate and reliable. However, results may not accurately reflect real people, places or facts.")
    b+=p("10.3. Users understand that:")
    b+=ul(["Results may contain errors or incorrect information","They should not rely on results as a single source of information","They should assess accuracy before using or sharing","Results may be incomplete, incorrect or offensive"])
    b+=h2("Digital Marketing","s10",cap=S+" 10")
    b+=p("11.1. Upon registering, the User acknowledges that they may receive promotional marketing materials from our strategic partners.")
    b+=p('11.2. The User may opt out of communications by sending a request to <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("11.3. MyDose may send communications via social networks (Facebook, Instagram, Google, LinkedIn) and WhatsApp.")
    b+=h2("Consent","s11",cap=S+" 11")
    b+=p("12.1. The User consents to receive documents and information through electronic communication.")
    b+=p("12.2. MyDose may contact via e-mail, SMS, push notifications, WhatsApp and phone.")
    b+=p("12.2.1. The User consents that MyDose and Leader Users may use and share their personal information for health examinations and studies.")
    b+=p("12.2.3. MyDose may share anonymized data with partners for profile analysis, analytical studies and marketing campaigns.")
    b+=h2("Intellectual Property","s12",cap=S+" 12")
    b+=p("12.1. MyDose may use the Leader User's brand in its portfolio for promotion.")
    b+=p("12.2. MyDose and users undertake not to harm intellectual property rights.")
    b+=p("12.3. All Intellectual Property rights in the app belong to MyDose or are licensed to it.")
    b+=p("12.4. No provision transfers MyDose's patent, trade secret, source code, design, technological systems or artificial intelligence rights to users.")
    b+=h2("Support and Contact","s13",cap=S+" 13")
    b+=p("MyDose provides support to Leader Users for technical questions and guidance. Users should seek support directly from the Leader Users of their Communities.")
    b+=contact([("E-mail",'<a href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>'),("Hours","9am to 5pm, Mon–Fri"),("Company","My Dose LLC — Delaware, USA")])
    b+=h2("Community Content","s14",cap=S+" 14")
    b+=p("When using MyDose's community and sharing features, the user agrees not to post offensive, hateful, sexually explicit or violent content. We reserve the right to remove any reported content within 24 hours and to ban users who violate these rules, maintaining a zero-tolerance policy for abuse.")
    return b

def build_es():
    S="Sección"; b=""
    b+=p("Estos Términos y Condiciones se aplican a la app MyDose y a la plataforma web MyDose, solución ofrecida por My Dose LLC, empresa constituida en Delaware — Estados Unidos. Al utilizar la plataforma, usted acepta tácita e íntegramente las disposiciones aquí contenidas. Si no está cómodo aceptando estos T&C, no podrá usar la plataforma y los servicios de MyDose.", lead=True)
    b+=h2("Aceptación de los Términos y Condiciones","s1",cap=S+" 1")
    b+=p("1.1. Estos T&C contienen información importante y el usuario debe leerlos antes de solicitar la activación de su adhesión a la aplicación.")
    b+=p('1.2. La versión actualizada está disponible en nuestros portales o por el correo <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("1.3. Cuando marca 'Leí y estoy de acuerdo', está diciendo que leyó, entendió y acepta seguir las reglas.")
    b+=p("1.4. MyDose puede modificar estos T&C en cualquier momento. Siempre que haya una actualización significativa, le informaremos por correo o notificaciones en la plataforma.")
    b+=p("1.5. Requisitos para el registro: proporcionar un correo válido, un número de identificación, y declarar estar en condiciones físicas y mentales para participar en las Comunidades.")
    b+=p("1.6. Los menores de 18 años ('Usuarios Menores') necesitan el consentimiento expreso del responsable legal a través de 'Cuenta Vinculada'.")
    b+=h2("Definiciones","s2",cap=S+" 2")
    b+=ul(["<strong>Contenido:</strong> todo lo que los usuarios comparten (textos, fotos, videos, audios, e-books)","<strong>Comunidad:</strong> espacio virtual para compartir hábitos saludables","<strong>Comunidad Privada:</strong> creada por Líderes para impulsar sus negocios","<strong>Comunidad Pública:</strong> abierta al público","<strong>Plataforma MyDose:</strong> aplicaciones para recorridos de bienestar físico, nutricional y mental","<strong>Usuario:</strong> persona física con perfil en la plataforma","<strong>Usuario Líder:</strong> persona que contrata un plan de suscripción para crear Comunidades","<strong>Usuario Gestor:</strong> persona que ayuda al Líder en la gestión de la Comunidad"])
    b+=h2("Qué es MyDose","s3",cap=S+" 3")
    b+=p("3.1. La Plataforma MyDose ofrece recorridos de bienestar físico, nutricional y mental, así como orientaciones de salud.")
    b+=p("3.2. El usuario puede compartir su recorrido y evolución con otros usuarios, generando participación y potenciando prácticas saludables.")
    b+=p("3.3. MyDose cree en la fuerza de la Comunidad y en el poder de la colaboración para crear y mantener hábitos saludables.")
    b+=p("3.4. MyDose es una plataforma digital enfocada en la gestión eficiente de Comunidades en línea, brindando herramientas para creación, personalización y administración.")
    b+=h2("Código de Adhesión","s4",cap=S+" 4")
    b+=p("4.1. El código de adhesión es el correo del Usuario.")
    b+=p("4.2. La adhesión es personal e intransferible. El Usuario es responsable de la custodia del código, quedando prohibida su divulgación a terceros.")
    b+=p("4.3. El Usuario debe comunicar inmediatamente a MyDose sobre cualquier uso no autorizado.")
    b+=p("4.4. El Usuario acepta:")
    b+=ul(["No usar la plataforma con fines fraudulentos o ilegales","Notificar cualquier uso no autorizado","Solicitar una nueva contraseña si sospecha un compromiso","Usar la plataforma de buena fe"])
    b+=h2("Servicios Prestados","s5",cap=S+" 5")
    b+=p("5.1. MyDose concede una licencia personal, no exclusiva e intransferible para usar los Servicios.")
    b+=p("5.2. La plataforma permite:")
    b+=ul(["Creación y gestión de Comunidades gamificadas","Herramientas para cambios de comportamiento","Sistema de recompensas y reconocimiento","Analítica e informes de progreso","Integración con herramientas de terceros","Interacciones con inteligencia artificial","Funciones de comunicación y participación"])
    b+=p("5.3. Pueden agregarse nuevas funcionalidades y modificarse las existentes en cualquier momento.")
    b+=h2("Planes y Cancelación","s6",cap=S+" 6")
    b+=p("6.1. Los Usuarios pueden participar gratuitamente en Comunidades Públicas y Privadas.")
    b+=p("6.2. Los Usuarios Líderes contratan planes de suscripción (mensual, trimestral, semestral o anual).")
    b+=p("6.3. Todos los planes SE RENUEVAN AUTOMÁTICAMENTE hasta que se solicite la cancelación.")
    b+=p("7.1. Los Usuarios Líderes pueden cancelar en cualquier momento, con efectos hasta la próxima recurrencia.")
    b+=p("7.2. Reembolso disponible dentro de los 7 días del pago. Después de este plazo, no hay reembolso.")
    b+=p('7.5. Las SOLICITUDES DE CANCELACIÓN deben enviarse por correo a <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a> con 20 días de antelación a la renovación.')
    b+=h2("Obligaciones y Responsabilidades","s7",cap=S+" 7")
    b+=p("8.1. El usuario es responsable de todas las manifestaciones, contenidos ingresados e interacciones realizadas.")
    b+=p("8.2. Las conductas prohibidas incluyen:")
    b+=ul(["Publicar información incorrecta o crear una identidad falsa","Usar la cuenta de otra persona","Realizar ingeniería inversa de la aplicación","Interferir en el funcionamiento o la seguridad","Acceder a áreas no autorizadas","Usar bots, scripts o extracción de datos","Acosar o perjudicar a otros usuarios","Violar derechos de propiedad intelectual"])
    b+=p("8.3. Contenidos prohibidos: datos de terceros sin autorización, contenido ilegal, discriminatorio, virus o malware.")
    b+=h2("Limitación de Responsabilidad","s8",cap=S+" 8")
    b+=p("9.1. MyDose no es responsable por datos incorrectos o incompletos proporcionados.")
    b+=p("9.2. La aplicación NO sustituye la atención médica, nutricional o de un profesional de salud. El Usuario es responsable de su propia salud.")
    b+=p("9.3. MyDose se exime de responsabilidad por actos de Usuarios Líderes y Usuarios que causen daños.")
    b+=p("9.4. MyDose no es responsable por contenidos publicados en las Comunidades.")
    b+=p("9.5. Los contratos entre Usuarios Líderes y Usuarios no vinculan a MyDose.")
    b+=p("9.10. Los Usuarios Líderes son responsables de administrar sus comunidades de forma ética y de toda la relación con sus Usuarios.")
    b+=h2("MyDose Inteligencia Artificial","s9",cap=S+" 9")
    b+=p("10.1. Partes de los servicios pueden incluir tecnologías de inteligencia artificial o aprendizaje automático.")
    b+=p("10.2. MyDose trabaja para hacer los servicios más precisos y confiables. Sin embargo, los resultados pueden no reflejar con precisión a personas, lugares o hechos reales.")
    b+=p("10.3. Los usuarios entienden que:")
    b+=ul(["Los resultados pueden contener errores o información incorrecta","No deben confiar en los resultados como única fuente de información","Deben evaluar la precisión antes de utilizar o compartir","Los resultados pueden ser incompletos, incorrectos u ofensivos"])
    b+=h2("Marketing Digital","s10",cap=S+" 10")
    b+=p("11.1. Al registrarse, el Usuario reconoce que puede recibir materiales promocionales de marketing de nuestros socios estratégicos.")
    b+=p('11.2. El Usuario puede optar por no recibir comunicaciones enviando una solicitud a <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("11.3. MyDose podrá enviar comunicaciones vía redes sociales (Facebook, Instagram, Google, LinkedIn) y WhatsApp.")
    b+=h2("Consentimiento","s11",cap=S+" 11")
    b+=p("12.1. El Usuario consiente recibir documentos e información por comunicación electrónica.")
    b+=p("12.2. MyDose puede contactar vía correo, SMS, notificaciones push, WhatsApp y teléfono.")
    b+=p("12.2.1. El Usuario consiente que MyDose y los Usuarios Líderes puedan usar y compartir su información personal para exámenes y estudios de salud.")
    b+=p("12.2.3. MyDose puede compartir datos anonimizados con socios para análisis de perfil, estudios analíticos y campañas de marketing.")
    b+=h2("Propiedad Intelectual","s12",cap=S+" 12")
    b+=p("12.1. MyDose puede usar la marca del Usuario Líder en su portafolio para divulgación.")
    b+=p("12.2. MyDose y los usuarios se comprometen a no perjudicar los derechos de propiedad intelectual.")
    b+=p("12.3. Todos los derechos de Propiedad Intelectual de la aplicación pertenecen a MyDose o están licenciados a él.")
    b+=p("12.4. Ninguna disposición transfiere derechos de patente, secreto comercial, código fuente, diseños, sistemas tecnológicos o inteligencia artificial de MyDose a los usuarios.")
    b+=h2("Soporte y Contacto","s13",cap=S+" 13")
    b+=p("MyDose ofrece soporte a los Usuarios Líderes para cuestiones técnicas y orientaciones. Los Usuarios deben buscar soporte directamente con los Usuarios Líderes de sus Comunidades.")
    b+=contact([("Correo",'<a href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>'),("Horario","9h a 17h, lun–vie"),("Empresa","My Dose LLC — Delaware, EE. UU.")])
    b+=h2("Contenido de la Comunidad","s14",cap=S+" 14")
    b+=p("Al utilizar las funcionalidades de comunidad y compartición de MyDose, el usuario acepta no publicar contenido ofensivo, de odio, sexualmente explícito o violento. Nos reservamos el derecho de eliminar cualquier contenido denunciado en un plazo de 24 horas y de banear a los usuarios que violen estas reglas, manteniendo una política de tolerancia cero ante los abusos.")
    return b

def build(lang):
    return build_en() if lang=="en" else build_es()
