# -*- coding: utf-8 -*-
"""Traduções EN/ES da Política de Privacidade (versão de cortesia; PT é a oficial)."""
from blocks import h2, h3, p, ul, callout, contact

def build_en():
    C="Chapter"; b=""
    b+=p("Hello User, thank you for using the MyDose app. My Dose LLC is committed to complying with the laws that protect the privacy of Users' data and the general public. To provide the services related to the MyDose app, it is necessary to process and share personal data. BY USING THE MYDOSE APP, THE USER TACITLY AND FULLY AGREES TO THE PROVISIONS CONTAINED HEREIN.", lead=True)
    b+=h2("General Provisions","ch1",cap=C+" I")
    b+=p("1.1. The MyDose app places the utmost importance on the relationship with its Users and their personal data. This Privacy Policy was created to communicate our practices for collecting, using and disclosing information.")
    b+=p("1.2. Personal information is data provided by Users that can be used to identify them individually.")
    b+=p("1.3. Sensitive personal information includes data on racial or ethnic origin, religious beliefs, political opinions and health data, as set out in Law 13.709/18 (LGPD).")
    b+=p("1.4. BY USING THE MYDOSE APP, YOU AUTHORIZE THE COLLECTION, USE AND DISCLOSURE OF INFORMATION ABOUT YOU, UNDER THE TERMS OF THIS POLICY.")
    b+=p("1.5. The MyDose app operates in compliance with Brazilian legislation, including Law No. 12.965/2014 (Brazilian Civil Rights Framework for the Internet) and Law No. 13.709/2018 (LGPD).")
    b+=p('1.6. If you have any questions, please contact us at <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("1.7. This Policy describes what information may be collected about Users and how it may be used.")
    b+=h2("Information Collected","ch2",cap=C+" II")
    b+=p("2.1. Data collected from Users:")
    b+=ul(["Full name","Valid e-mail address","Date of birth","Age","Physical health, mental wellbeing, personal budget and nutrition information"])
    b+=p("2.1.1. Personal data is collected in various circumstances, including registration in the app and activation of features.")
    b+=p("2.1.2. Sensitive personal data is also collected, such as physical activity data, medical and health information from connected devices (Google Fit, Apple Health, Samsung Health, Strava, Garmin, etc.).")
    b+=p("2.1.3. Users may choose to connect and share information from partner apps with MyDose.")
    b+=p("2.1.4. Information collected by partners and third parties is subject to their own terms and policies.")
    b+=p("2.2. Data collected from Leader Users:")
    b+=ul(["Full name","Valid e-mail address","Phone","Tax ID (CPF or CNPJ)","Full address","Credit card data"])
    b+=p("2.3. Collection of minors' data will be carried out with the consent of the Legal Guardian.")
    b+=p('2.4. <strong>Data obtained through Google APIs.</strong> When a Leader User chooses to connect their Google account, MyDose requests access to the following Google API scopes:')
    b+=ul(['<code>https://www.googleapis.com/auth/calendar.events</code> — to create calendar events (with a Google Meet link) in the professional\'s Google Calendar when an online appointment is scheduled on the platform.',
           '<code>https://www.googleapis.com/auth/userinfo.email</code> — to identify and display which Google account was connected.'])
    b+=p('The processing of all data obtained through these Google APIs is governed exclusively by <strong>Chapter XIV (Google User Data — Limited Use)</strong> below, which prevails over any provision to the contrary in this Policy.')
    b+=h2("How We Use Information","ch3",cap=C+" III")
    b+=p("3.1. MyDose uses the collected information to:")
    b+=ul(["a) Identify and register Users and provide the app's services","b) Ensure content is presented in the most efficient way","c) Make general improvements to the app","d) Give HR Administrators access to data for analysis and reports","e) Contact and notify Users about changes to the platform","f) Conduct statistical research","g) Feed the MyDose Data Lake database","h) Promotional or marketing purposes","i) Develop personalized solutions for a healthier life"])
    b+=p("3.2. Additional non-personal information may be used for any purpose.")
    b+=p("3.3. <strong>MYDOSE KEEPS INTERNET ACCESS RECORDS CONFIDENTIAL, IN A CONTROLLED AND SECURE ENVIRONMENT, WITH ENCRYPTION IN TRANSIT.</strong>")
    b+=p("3.4. Sensitive medical information will not be used in future underwriting or claims decisions.")
    b+=p("3.5. MyDose services are not intended to diagnose, cure, mitigate, treat or prevent any condition, nor do they replace professional medical care.")
    b+=p("3.6. The uses described in items 3.1(d), 3.1(f), 3.1(g), 3.1(h) and 3.2 do NOT apply to data obtained through Google APIs. That data is used solely as described in Chapter XIV.")
    b+=h2("Sharing of Information","ch4",cap=C+" IV")
    b+=p("4.1. MyDose does not disclose to third parties any information provided by the User, except:")
    b+=ul(["a) To comply with a legal obligation or prevent fraud","b) To protect MyDose's rights, property or safety","c) With police or governmental authorities","d) Upon prior notice and consent of the User","e) By the User's own action, such as sharing with Community Leaders","f) For statistical or authorial research","g) With third-party service providers in compliance with privacy standards","h) With agents, contractors or third-party service providers","i) With contracted third-party servers that store the database (Google Cloud Platform, Supabase)","j) In case of sale, merger or corporate restructuring"])
    b+=p("4.2. <strong>International sharing.</strong> MyDose uses Google Cloud Platform services to store and process data, which may be transferred to the United States.")
    b+=p("4.3. <strong>Sharing with AI.</strong> User data (excluding data obtained through Google APIs) may be shared via API integration with Gemini (Google AI) for reports, process automation and automated interactions. Data obtained through Google APIs is never transmitted to AI services, as per Chapter XIV.")
    b+=p("4.4. <strong>Non-disclosure.</strong> Except in the situations above, MyDose will not disclose any personal information.")
    b+=p("4.5. THE USER HAS THE RIGHT NOT TO ACCEPT THESE TERMS AND TO REMOVE THEIR DATA.")
    b+=p("4.6. By accepting these terms, the User authorizes the sharing of data. The User may revoke consent at any time, including by disconnecting their Google account.")
    b+=p("4.7. MyDose will retain the User's data for as long as the User remains registered or while there is a legitimate interest of the company.")
    b+=p("4.8. The sharing permitted by items 4.1(f), 4.1(g), 4.1(h) and 4.3 does NOT apply to data obtained through Google APIs, except when strictly necessary to provide user-facing functionality, as detailed in Chapter XIV.")
    b+=h2("Cookies","ch5",cap=C+" V")
    b+=p("5.1. A cookie is information stored locally on the User's device containing data about their Internet activities.")
    b+=p("5.2. Cookies used:")
    b+=ul(["<strong>Performance Cookies:</strong> collect anonymous information about platform usage","<strong>Functional Cookies:</strong> provide a better browsing experience"])
    b+=p("5.3. Access to cookies ends when the User closes the browser. You can accept or refuse cookies in your browser settings.")
    b+=p("5.4. The User's acceptance is required before cookies are used.")
    b+=p("5.5. If you choose to refuse cookies, access to most of the available information may be compromised.")
    b+=h2("Access and Correction of Personal Information","ch6",cap=C+" VI")
    b+=p("6.1. MyDose will take all appropriate measures to update and correct identifiable personal information.")
    b+=p("6.2. The User has the right to access, modify, correct and delete their data at any time.")
    b+=p("6.3. It is the User's responsibility to keep their personal information up to date.")
    b+=p("6.3.1. The User is responsible for the information entered in the app, affirming that they have reviewed its accuracy, including when information is extracted by artificial intelligence.")
    b+=p('6.4. The User has the right to access their personal information under Law No. 12.965/2014 and Law No. 13.709/2018, by contacting <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("6.5. MyDose adopts all necessary measures to protect personal information against loss, misuse and unauthorized access, with encryption and strict security standards.")
    b+=p("6.6. The User is responsible for protecting their passwords and access credentials.")
    b+=h2("Notification of Changes to the Privacy Policy","ch7",cap=C+" VII")
    b+=p("7.1. MyDose may change the Privacy Policy periodically. Should there be changes in the use of personal information, Users will be notified through announcements on the platform or by e-mail.")
    b+=p("7.2. Continued use of the services after any change constitutes acceptance of the modified Policy.")
    b+=p("7.3. Minor adjustments may occur without prior notice.")
    b+=h2("Use of Artificial Intelligence (AI) Features","ch8",cap=C+" VIII")
    b+=p("Our app may offer optional features based on third-party Artificial Intelligence services (for example, Gemini / Google AI) to assist in generating health summaries or suggestions.")
    b+=p("<strong>Data sharing:</strong> By choosing to use these features, specific text inputs or data explicitly selected by you may be transmitted to the AI provider for processing. Data obtained through Google APIs (such as Google Calendar data) is excluded and never transmitted to AI services.")
    b+=p("<strong>Consent:</strong> By using these AI features, you consent to this data transfer.")
    b+=p("<strong>Notice:</strong> All AI-generated content is for informational purposes only and is reviewed by your healthcare professional. It does not constitute medical advice.")
    b+=p("<strong>Data retention:</strong> We do not allow third-party AI providers to use your personal data to train their models.")
    b+=h2("Use of E-mail","ch9",cap=C+" IX")
    b+=p("9.1. Upon registering, the User agrees to receive notifications, news and important information by e-mail.")
    b+=p('9.1.1. The User may opt out using the opt-out feature or by requesting removal via <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("9.1.2. Administrative e-mails related to account maintenance cannot be cancelled.")
    b+=p("9.1.3. The use of MyDose for Spam is absolutely prohibited.")
    b+=p("9.2. Maximum confidentiality is guaranteed in the handling of Users' e-mail addresses.")
    b+=p("9.2.1. The User is guaranteed the ability to remove their e-mail address.")
    b+=h2("Prohibitions","ch10",cap=C+" X")
    b+=p("10.1. MyDose reserves the right to refuse or remove any connection that contains incorrect information or unfounded claims.")
    b+=h2("Security of Personal Information","ch11",cap=C+" XI")
    b+=p("11.1. The MyDose app uses data encryption. Information is hosted on servers in the United States, accessible only by authorized employees.")
    b+=p("11.2. If MyDose becomes aware of any security breach, it will immediately notify affected Users.")
    b+=p("11.3. MyDose may copy, disclose, distribute, incorporate and use materials and data for commercial or non-commercial purposes, in accordance with this Policy. <strong>This provision does NOT apply to data obtained through Google APIs, which is governed exclusively by Chapter XIV.</strong>")
    b+=p("11.4. The User will be responsible for indemnifying MyDose for costs arising from violations of this Policy.")
    b+=p("11.5. MyDose cooperates with authorities that request the identification of persons who violate these provisions.")
    b+=p("11.6. This Policy addresses only the use and disclosure of information collected by MyDose. MyDose does not control the privacy policies of third parties.")
    b+=h2("Digital Marketing","ch12",cap=C+" XII")
    b+=p('12.1. By joining the MyDose app, the User understands and acknowledges that MyDose may send marketing communications through social networks such as Facebook, Instagram, Google, LinkedIn, etc. MyDose may also contact Users via WhatsApp. The User may opt out of marketing communications by sending a request to <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("12.2. <strong>Data obtained through Google APIs is never used for marketing, advertising or any promotional purpose, as per Chapter XIV.</strong>")
    b+=h2("Contact","ch13",cap=C+" XIII")
    b+=p("13.1. The User may contact MyDose at any time to share opinions about privacy practices or questions related to their personal information:")
    b+=contact([("E-mail",'<a href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>'),("Phone","+1 424-537-2605"),("Address","Los Angeles, California — USA")])
    b+=h2("Google User Data — Limited Use","ch14",cap=C+" XIV")
    b+=p("MyDose's use and transfer of any information received from Google APIs — including the <code>calendar.events</code> and <code>userinfo.email</code> scopes — adheres to the Google API Services User Data Policy, including the Limited Use requirements.")
    b+=p("Specifically, <strong>data obtained through Google APIs is used solely to provide and improve the user-facing features</strong> for which the user granted access. The <code>calendar.events</code> scope is used only to create calendar events (with a Google Meet link) in the professional's Google Calendar when an online appointment is scheduled on the platform. The <code>userinfo.email</code> scope is used only to identify and display which Google account was connected.")
    b+=p("MyDose does not:")
    b+=ul(["use Google user data for advertising, marketing or any promotional purpose;","sell Google user data, nor transfer it to third parties, except as necessary to provide or improve user-facing functionality, to comply with applicable law, or as part of a merger or acquisition with notice to the user;","use or transfer Google user data to develop, improve or train generalized or non-personalized artificial intelligence and/or machine learning models, including third-party AI services such as Gemini;","allow humans to read Google user data, except when: (a) the user provides prior explicit consent; (b) it is necessary for security purposes; (c) it is required to comply with applicable law; or (d) the data is aggregated and anonymized and used for internal operations."])
    b+=p("This Chapter XIV prevails over any provision to the contrary in this Policy. The provisions of Chapters III, IV, VIII, XI and XII regarding marketing, data aggregation, Data Lake, commercial use, third-party sharing and AI processing do not apply to data obtained through Google APIs.")
    b+=p("Users may revoke MyDose's access to their Google data at any time by disconnecting their Google account within the app, or via the Google Account permissions page.")
    b+=callout("Google API Services User Data Policy","<p>MyDose's use and transfer of information received from Google APIs to any other app will adhere to the <a class='inl' href='https://developers.google.com/terms/api-services-user-data-policy' target='_blank' rel='noopener'>Google API Services User Data Policy</a>, including the Limited Use requirements. MyDose does not use or transfer data obtained through Google Workspace APIs to develop, improve, or train generalized artificial intelligence and/or machine learning models.</p>", warn=False)
    return b

def build_es():
    C="Capítulo"; b=""
    b+=p("Hola Usuario, gracias por acceder a la aplicación MyDose. My Dose LLC tiene el compromiso de cumplir las leyes que protegen la privacidad de los datos de los Usuarios y del público en general. Para prestar los servicios relacionados con la aplicación MyDose, es necesario tratar y compartir datos personales. AL UTILIZAR LA APLICACIÓN MYDOSE, EL USUARIO ACEPTA TÁCITA E ÍNTEGRAMENTE LAS DISPOSICIONES AQUÍ CONTENIDAS.", lead=True)
    b+=h2("Disposiciones Generales","ch1",cap=C+" I")
    b+=p("1.1. La aplicación MyDose considera de suma importancia la relación con sus Usuarios y sus datos personales. Esta Política de Privacidad fue elaborada para comunicar nuestras prácticas de recopilación, uso y divulgación de información.")
    b+=p("1.2. La información personal son datos proporcionados por los Usuarios que pueden utilizarse para identificarlos individualmente.")
    b+=p("1.3. La información personal sensible incluye datos sobre origen racial o étnico, convicciones religiosas, opiniones políticas y datos de salud, conforme lo estipulado por la Ley 13.709/18 (LGPD).")
    b+=p("1.4. AL UTILIZAR LA APLICACIÓN MYDOSE, USTED AUTORIZA LA RECOPILACIÓN, EL USO Y LA DIVULGACIÓN DE INFORMACIÓN SOBRE USTED, EN LOS TÉRMINOS DE ESTA POLÍTICA.")
    b+=p("1.5. La aplicación MyDose opera de conformidad con la legislación brasileña, incluyendo la Ley n.º 12.965/2014 (Marco Civil de Internet) y la Ley n.º 13.709/2018 (LGPD).")
    b+=p('1.6. En caso de dudas, contáctenos por el correo <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("1.7. Esta Política describe qué información puede recopilarse sobre los Usuarios y cómo puede utilizarse.")
    b+=h2("Información Recopilada","ch2",cap=C+" II")
    b+=p("2.1. Datos recopilados de los Usuarios:")
    b+=ul(["Nombre completo","Dirección de correo electrónico válida","Fecha de nacimiento","Edad","Información de salud física, bienestar mental, presupuesto personal y nutrición"])
    b+=p("2.1.1. Los datos personales se recopilan en diversas circunstancias, incluyendo el registro en la aplicación y la activación de funcionalidades.")
    b+=p("2.1.2. También se recopilan datos personales sensibles, tales como datos de actividad física, información médica y de salud provenientes de dispositivos conectados (Google Fit, Apple Health, Samsung Health, Strava, Garmin, etc.).")
    b+=p("2.1.3. Los Usuarios pueden optar por conectar y compartir información de aplicaciones asociadas con MyDose.")
    b+=p("2.1.4. La información recopilada por socios y terceros está sujeta a sus propios términos y políticas.")
    b+=p("2.2. Datos recopilados de los Usuarios Líderes:")
    b+=ul(["Nombre completo","Dirección de correo electrónico válida","Teléfono","Identificación fiscal (CPF o CNPJ)","Dirección completa","Datos de tarjeta de crédito"])
    b+=p("2.3. La recopilación de datos de menores se realizará mediante el consentimiento del Responsable.")
    b+=p('2.4. <strong>Datos obtenidos mediante las API de Google.</strong> Cuando un Usuario Líder opta por conectar su cuenta de Google, MyDose solicita acceso a los siguientes ámbitos de la API de Google:')
    b+=ul(['<code>https://www.googleapis.com/auth/calendar.events</code> — para crear eventos de calendario (con enlace de Google Meet) en el Google Calendar del profesional cuando se agenda una consulta en línea en la plataforma.',
           '<code>https://www.googleapis.com/auth/userinfo.email</code> — para identificar y mostrar qué cuenta de Google fue conectada.'])
    b+=p('El tratamiento de todos los datos obtenidos mediante estas API de Google se rige exclusivamente por el <strong>Capítulo XIV (Google User Data — Limited Use)</strong> a continuación, que prevalece sobre cualquier disposición en contrario de esta Política.')
    b+=h2("Cómo Usamos la Información","ch3",cap=C+" III")
    b+=p("3.1. MyDose utiliza la información recopilada para:")
    b+=ul(["a) Identificar y registrar Usuarios y prestar los servicios de la aplicación","b) Garantizar que el contenido se presente de la forma más eficiente","c) Realizar mejoras generales en la aplicación","d) Ofrecer a los Administradores de RR.HH. acceso a los datos para análisis e informes","e) Contactar y notificar a los Usuarios sobre cambios en la plataforma","f) Realizar investigaciones estadísticas","g) Alimentar la base de datos Data Lake de MyDose","h) Fines promocionales o de marketing","i) Desarrollar soluciones personalizadas para una vida más saludable"])
    b+=p("3.2. La información adicional no personal puede utilizarse para cualquier finalidad.")
    b+=p("3.3. <strong>MYDOSE MANTIENE LOS REGISTROS DE ACCESO A INTERNET BAJO CONFIDENCIALIDAD, EN UN ENTORNO CONTROLADO Y SEGURO, CON CIFRADO EN TRÁNSITO.</strong>")
    b+=p("3.4. La información médica sensible no se utilizará en decisiones futuras de suscripción o siniestros.")
    b+=p("3.5. Los servicios de MyDose no están destinados a diagnosticar, curar, mitigar, tratar o prevenir ninguna condición, ni sustituyen la atención médica profesional.")
    b+=p("3.6. Los usos descritos en los ítems 3.1(d), 3.1(f), 3.1(g), 3.1(h) y 3.2 NO se aplican a los datos obtenidos mediante las API de Google. Esos datos se utilizan únicamente según lo descrito en el Capítulo XIV.")
    b+=h2("Compartición de Información","ch4",cap=C+" IV")
    b+=p("4.1. MyDose no divulga a terceros ninguna información proporcionada por el Usuario, excepto:")
    b+=ul(["a) Para cumplir una obligación legal o prevenir fraudes","b) Para proteger los derechos, la propiedad o la seguridad de MyDose","c) Con autoridades policiales o gubernamentales","d) Mediante notificación y consentimiento previos del Usuario","e) Por acción del propio Usuario, como compartir con Líderes de Comunidad","f) Para investigación estadística o autoral","g) Con empresas terceras prestadoras de servicios en conformidad con estándares de privacidad","h) Con agentes, contratistas o prestadores de servicios terceros","i) Con servidores terceros contratados que almacenan la base de datos (Google Cloud Platform, Supabase)","j) En caso de venta, fusión o reestructuración empresarial"])
    b+=p("4.2. <strong>Compartición internacional.</strong> MyDose utiliza servicios de Google Cloud Platform para almacenar y procesar datos, que pueden transferirse a los Estados Unidos.")
    b+=p("4.3. <strong>Compartición con IA.</strong> Los datos de los Usuarios (excluidos los datos obtenidos mediante las API de Google) pueden compartirse mediante integración de API con Gemini (Google AI) para informes, automatización de procesos e interacciones automatizadas. Los datos obtenidos mediante las API de Google nunca se transmiten a servicios de IA, conforme al Capítulo XIV.")
    b+=p("4.4. <strong>No divulgación.</strong> Salvo en las situaciones anteriores, MyDose no divulgará ninguna información personal.")
    b+=p("4.5. EL USUARIO TIENE DERECHO A NO ACEPTAR ESTOS TÉRMINOS Y A ELIMINAR SUS DATOS.")
    b+=p("4.6. Al aceptar estos términos, el Usuario autoriza la compartición de datos. El Usuario puede revocar el consentimiento en cualquier momento, incluso desconectando su cuenta de Google.")
    b+=p("4.7. MyDose conservará los datos del Usuario mientras este permanezca registrado o mientras exista un interés legítimo de la empresa.")
    b+=p("4.8. La compartición permitida por los ítems 4.1(f), 4.1(g), 4.1(h) y 4.3 NO se aplica a los datos obtenidos mediante las API de Google, salvo cuando sea estrictamente necesario para proveer la funcionalidad orientada al usuario, según se detalla en el Capítulo XIV.")
    b+=h2("Cookies","ch5",cap=C+" V")
    b+=p("5.1. Una cookie es información almacenada localmente en el dispositivo del Usuario que contiene datos sobre sus actividades en Internet.")
    b+=p("5.2. Cookies utilizadas:")
    b+=ul(["<strong>Cookies de Rendimiento:</strong> recopilan información anónima sobre el uso de la plataforma","<strong>Cookies Funcionales:</strong> proporcionan una mejor experiencia de navegación"])
    b+=p("5.3. El acceso a las cookies termina cuando el Usuario cierra el navegador. Puede aceptar o rechazar cookies en la configuración del navegador.")
    b+=p("5.4. Se requiere la aceptación del Usuario antes del uso de cookies.")
    b+=p("5.5. Si opta por rechazar las cookies, el acceso a la mayor parte de la información disponible puede verse comprometido.")
    b+=h2("Acceso y Corrección de Información Personal","ch6",cap=C+" VI")
    b+=p("6.1. MyDose adoptará todas las medidas adecuadas para actualizar y corregir la información personal identificable.")
    b+=p("6.2. El Usuario tiene derecho a acceder, modificar, corregir y eliminar sus datos en cualquier momento.")
    b+=p("6.3. Es responsabilidad del Usuario mantener su información personal actualizada.")
    b+=p("6.3.1. El Usuario es responsable de la información ingresada en la aplicación, afirmando que ha revisado su exactitud, incluso cuando la información sea extraída por inteligencia artificial.")
    b+=p('6.4. El Usuario tiene derecho a acceder a su información personal en los términos de la Ley n.º 12.965/2014 y la Ley n.º 13.709/2018, contactando a <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("6.5. MyDose adopta todas las medidas necesarias para proteger la información personal contra pérdida, uso indebido y acceso no autorizado, con cifrado y estándares rigurosos de seguridad.")
    b+=p("6.6. El Usuario es responsable de la protección de sus contraseñas y credenciales de acceso.")
    b+=h2("Notificación de Modificaciones de la Política de Privacidad","ch7",cap=C+" VII")
    b+=p("7.1. MyDose puede modificar la Política de Privacidad periódicamente. En caso de cambios en el uso de información personal, los Usuarios serán notificados mediante anuncios en la plataforma o por correo electrónico.")
    b+=p("7.2. El uso continuado de los servicios tras cualquier cambio constituye la aceptación de la Política modificada.")
    b+=p("7.3. Pueden ocurrir ajustes menores sin previo aviso.")
    b+=h2("Uso de Funcionalidades de Inteligencia Artificial (IA)","ch8",cap=C+" VIII")
    b+=p("Nuestra aplicación puede ofrecer funcionalidades opcionales basadas en servicios de Inteligencia Artificial de terceros (por ejemplo, Gemini / Google AI) para ayudar en la generación de resúmenes o sugerencias de salud.")
    b+=p("<strong>Compartición de datos:</strong> Al optar por usar estas funcionalidades, entradas de texto específicas o datos explícitamente seleccionados por usted pueden transmitirse al proveedor de IA para su procesamiento. Los datos obtenidos mediante las API de Google (como datos de Google Calendar) quedan excluidos y nunca se transmiten a servicios de IA.")
    b+=p("<strong>Consentimiento:</strong> Al usar estas funcionalidades de IA, usted consiente esta transferencia de datos.")
    b+=p("<strong>Aviso:</strong> Todo contenido generado por IA tiene carácter meramente informativo y es revisado por su profesional de salud. No constituye asesoramiento médico.")
    b+=p("<strong>Retención de datos:</strong> No permitimos que los proveedores de IA de terceros utilicen sus datos personales para entrenar sus modelos.")
    b+=h2("Uso de Correo Electrónico","ch9",cap=C+" IX")
    b+=p("9.1. Al registrarse, el Usuario acepta recibir notificaciones, novedades e información importante por correo electrónico.")
    b+=p('9.1.1. El Usuario puede optar por darse de baja utilizando el opt-out o solicitando la eliminación vía <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("9.1.2. Los correos administrativos relacionados con el mantenimiento de la cuenta no pueden cancelarse.")
    b+=p("9.1.3. El uso de MyDose para Spam está absolutamente prohibido.")
    b+=p("9.2. Se garantiza la máxima confidencialidad en el tratamiento de las direcciones de correo de los Usuarios.")
    b+=p("9.2.1. Se garantiza al Usuario la posibilidad de eliminar su dirección de correo electrónico.")
    b+=h2("Prohibiciones","ch10",cap=C+" X")
    b+=p("10.1. MyDose se reserva el derecho de rechazar o eliminar cualquier conexión que contenga información incorrecta o afirmaciones infundadas.")
    b+=h2("Seguridad de la Información Personal","ch11",cap=C+" XI")
    b+=p("11.1. La aplicación MyDose utiliza cifrado de datos. La información está alojada en servidores en los Estados Unidos, con acceso solo por empleados autorizados.")
    b+=p("11.2. Si MyDose tiene conocimiento de cualquier violación de seguridad, notificará inmediatamente a los Usuarios afectados.")
    b+=p("11.3. MyDose puede copiar, divulgar, distribuir, incorporar y usar materiales y datos con fines comerciales o no comerciales, respetando esta Política. <strong>Esta disposición NO se aplica a los datos obtenidos mediante las API de Google, que se rigen exclusivamente por el Capítulo XIV.</strong>")
    b+=p("11.4. El Usuario será responsable de indemnizar a MyDose por los costos derivados de violaciones de esta Política.")
    b+=p("11.5. MyDose coopera con las autoridades que soliciten la identificación de personas que violen estas disposiciones.")
    b+=p("11.6. Esta Política trata únicamente del uso y la divulgación de información recopilada por MyDose. MyDose no controla las políticas de privacidad de terceros.")
    b+=h2("Marketing Digital","ch12",cap=C+" XII")
    b+=p('12.1. Al adherirse a la aplicación MyDose, el Usuario comprende y reconoce que MyDose puede enviar comunicaciones de marketing por redes sociales como Facebook, Instagram, Google, LinkedIn, etc. MyDose también puede contactar a los Usuarios vía WhatsApp. El Usuario puede optar por dejar de recibir comunicaciones de marketing enviando una solicitud a <a class="inl" href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>.')
    b+=p("12.2. <strong>Los datos obtenidos mediante las API de Google nunca se utilizan para marketing, publicidad o cualquier finalidad promocional, conforme al Capítulo XIV.</strong>")
    b+=h2("Contacto","ch13",cap=C+" XIII")
    b+=p("13.1. El Usuario puede contactar a MyDose en cualquier momento para compartir opiniones sobre prácticas de privacidad o dudas relacionadas con su información personal:")
    b+=contact([("Correo",'<a href="mailto:contact@mydoseapp.com">contact@mydoseapp.com</a>'),("Teléfono","+1 424-537-2605"),("Dirección","Los Ángeles, California — EE. UU.")])
    b+=h2("Google User Data — Limited Use","ch14",cap=C+" XIV")
    b+=p("El uso y la transferencia por parte de MyDose de cualquier información recibida de las API de Google — incluyendo los ámbitos <code>calendar.events</code> y <code>userinfo.email</code> — se rigen por la Google API Services User Data Policy, incluidos los requisitos de Limited Use.")
    b+=p("Específicamente, <strong>los datos obtenidos mediante las API de Google se utilizan únicamente para proveer y mejorar las funcionalidades orientadas al usuario</strong> para las cuales el usuario concedió acceso. El ámbito <code>calendar.events</code> se usa solo para crear eventos de calendario (con enlace de Google Meet) en el Google Calendar del profesional cuando se agenda una consulta en línea en la plataforma. El ámbito <code>userinfo.email</code> se usa solo para identificar y mostrar qué cuenta de Google fue conectada.")
    b+=p("MyDose no:")
    b+=ul(["utiliza datos de usuarios de Google para publicidad, marketing o cualquier finalidad promocional;","vende datos de usuarios de Google, ni los transfiere a terceros, salvo cuando sea necesario para proveer o mejorar la funcionalidad orientada al usuario, para cumplir la ley aplicable, o como parte de una fusión o adquisición con aviso al usuario;","usa o transfiere datos de usuarios de Google para desarrollar, mejorar o entrenar modelos generalizados o no personalizados de inteligencia artificial y/o aprendizaje automático, incluidos servicios de IA de terceros como Gemini;","permite que humanos lean datos de usuarios de Google, salvo cuando: (a) el usuario otorgue consentimiento previo explícito; (b) sea necesario por motivos de seguridad; (c) sea exigido para cumplir la ley aplicable; o (d) los datos estén agregados y anonimizados y se usen para operaciones internas."])
    b+=p("Este Capítulo XIV prevalece sobre cualquier disposición en contrario de esta Política. Las disposiciones de los Capítulos III, IV, VIII, XI y XII relativas a marketing, agregación de datos, Data Lake, uso comercial, compartición con terceros y procesamiento por IA no se aplican a los datos obtenidos mediante las API de Google.")
    b+=p("Los usuarios pueden revocar en cualquier momento el acceso de MyDose a sus datos de Google desconectando su cuenta de Google dentro de la aplicación, o mediante la página de permisos de la Cuenta de Google.")
    b+=callout("Google API Services User Data Policy","<p>MyDose's use and transfer of information received from Google APIs to any other app will adhere to the <a class='inl' href='https://developers.google.com/terms/api-services-user-data-policy' target='_blank' rel='noopener'>Google API Services User Data Policy</a>, including the Limited Use requirements. MyDose does not use or transfer data obtained through Google Workspace APIs to develop, improve, or train generalized artificial intelligence and/or machine learning models.</p>", warn=False)
    return b

def build(lang):
    return build_en() if lang=="en" else build_es()
